= Lastenheft
:toc: right

== Lehrstuhlbibliothek

=== 1. Zielbestimmung

Die Software soll eine digitale Verwaltung der Lehrstuhlbibliothek ermöglichen, die leicht verständlich und einfach zu bedienen ist. Das bedeutet unter anderem,
dass das System unabhängig durch Mitarbeiter verwaltet werden kann. Außerdem sollen Nutzer Zugriff über das Universitätsnetzwerk haben.

=== 2. Produkteinsatz
Der Zugriff auf die Software soll innerhalb des gesamten Universitätsnetzwerks der Technischen Universität Dresden möglich sein.

In das Netzwerk sind von der Universität standartisierte und private Rechnersysteme eingebunden.

=== 3. Produktübersicht

NOTE: Muss noch gemacht werden, nur haben wir keine Ahnung was zu tun ist. (Use-Case-Diagramms)

=== 4. Produktfunktionen

* Die Software soll alle Medien der Lehrstuhlbibliothek nach Typ katalogisieren. Diese können in verschieden Stückzahlen vorhanden sein.
* Das Interface soll übersichtlich und einfach zu bedienen sein.
* Die Software soll eine Rechteverwaltung in Form von Gruppenzugehörigkeit bereitstellen. Wobei innerhalb einer Gruppe jedes Mitglied die selben Rechte hat. Wichtige Gruppen:
** Systemadministrator
** Verwaltung
** Nutzergruppe
** Gastgruppe
* Der Administrator soll das Rechtesystem verwalten können. Insbesondere Gruppenrechte erweitern, einschränken und Gruppen erstellen/löschen.
* Die Verwaltung soll den Medienkatalog und den Nutzerkatalog bearbeiten können.
* Nutzer sind registriert. Sie sollen Medien ausleihen können.
* Gäste sollen nur eingeschränkte Rechte haben.
* Jede Person soll sich registrieren können. Die Registrierung muss von der Verwaltung bestätigt werden.
* Die Ausleihdauer soll durch das Medium und die Gruppenrechte vorgegeben werden (Minimum der beiden). Die Verwaltung soll die Ausleihdauer abändern können.
* Das Vorbestellen eines Mediums soll möglich sein.
* Die Verlängerung der Ausleihdauer soll jederzeit möglich sein, wenn das Medium nicht vorbestellt ist.
* Das System soll selbständig überfällige Ausleihfristen erkennen und Warnungen bzw. Mahnungen per E-Mail verschicken.
* Das System soll  eine Suche über die gesamten Kataloge (Nutzer/ Medien/ Ausleih-/ Vorbestellvorgänge) anbieten. Es soll eine Suche über Metadaten und Inhalt möglich sein.

=== 5. Produktdaten
==== Lieferumfang
Das Produkt muss installationsfertig auf einem gängigen Speichermedium (Flashdrive, CD/DVD, 3.5 '' Floppy Disk) ausgeliefert werden. Außerdem soll eine detaillierte Dokumentation im PDF-Format mit geliefert werden.
Die Dokumentation umfasst:

* Benutzerhandbuch
* Technisches Benutzerhandbuch
* Installationsanleitung

==== Kosten
Dem Angebot soll ein Kostenvoranschlag beiliegen, der detailliert Kosten aufzählt und zusammenrechnet.
Insbesondere soll ein Angebot für Wartung und Pflege beiliegen.

==== Liefertermin
Als Liefertermin für die Software ist der 31.11.2018 vorgesehen.

==== Ansprechstelle und Lieferort
Technische Universität Dresden
Fakultät Informatik
Herr Hermann Mann
Nöthnitzerstraße 46
01187 Dresden
Telefon 0351 123456789
Apparat 01

=== 6. Produktleistungen

*Suche von Medium in Katalog: 100ms bei 10.000 Medien im Katalog
*Suche von Benutzer in Mitarbeiterverwaltung : 200ms bei 10.000 Benutzern in der Datenbank
*Prüfen der Ausleihvorgänge auf Überfälligkeit: 5min bei 100.000 Ausleihvorgängen in der Datenbank

=== 7. Qualitätsanforderungen

* Die Lieferung ist wie im Abschnitt Lieferumfang erfolgt.
* Die Software läuft stabil auf den Rechnern der Universität.
* Alle in Produktfunktionen aufgelisteten Anforderungen müssen gewährleistet sein. Dies soll durch entsprechende Test nachgewiesen werden.
* Erfolgreicher Abschluss eines mindestens vierwöchigen Beta-Tests durch den Nutzerkreis.
